In [1]:
import numpy as np 
# numpy是专门用来处理矩阵等数据的库

In [4]:
a = np.arange(3,7,2)
# arrange类似range生成array的方法
a

array([3, 5])

In [11]:
a2 = a[np.newaxis,:]
a2.shape
# shape 表示出来矩阵的行列
# a2.ndim 维度 a2.size 大小

(1, 2)

In [13]:
# create array
a3 = np.zeros(4)
a3

array([0., 0., 0., 0.])

In [17]:
a4 = np.ones(5, dtype = np.int64) # change the float point to integer point
a4

array([1, 1, 1, 1, 1], dtype=int64)

In [16]:
np.linspace(0,10,num = 5)
# create an array with values that are spaced linearly in specific interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
# concatenate two array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
# reshape the array
a = np.arange(6)
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
# using newaxis will increase the dimension of the array
a = np.arange(6)
row_array = a[np.newaxis, :]
row_array.shape
row_array

array([[0, 1, 2, 3, 4, 5]])

In [28]:
col_array = a[:,np.newaxis]
col_array.shape
col_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
# another method to increase the dimension of the array
row_array2 = np.expand_dims(a, axis=0)
row_array2

array([[0, 1, 2, 3, 4, 5]])

In [31]:
col_array2 = np.expand_dims(a, axis = 1)
col_array2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
# select values from array that fullfill certain condition
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a>6]

array([ 7,  8,  9, 10, 11, 12])

In [37]:
condition = (a % 2 == 0) & (a < 11)
a[condition]
condition

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [40]:
# can also use some method below
b = np.nonzero(a < 5 )
b
# return two demensions, the frist is row and the second is col

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [41]:
# you can convert the array to coordinates
point_coordinates = list(zip(b[0],b[1]))
for point in point_coordinates:
    print(point)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [42]:
# you can find the value of the points using their coordinate array
a[b]

array([1, 2, 3, 4])

In [43]:
# when the array is 2D, they also can concatenate
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [46]:
np.vstack((a1,a2)) # vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
np.hstack((a1,a2)) # horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [48]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [52]:
# deep copy
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[0,:]
b[0] = 99
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
b = a[0,:].copy()
b[0] = 199
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
# we can add the arrays, sub arrays and so 
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [55]:
data.sum()

3

In [62]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis = 0) # sum rows
b.max(axis = 1)
b.min(axis = 0)

array([1, 1])

In [59]:
# operate array with a single number
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [63]:
# slice and matrice
data = np.array([[1, 2], [3, 4], [5, 6]])
data[0:2,0] # the rows which col is 0

array([1, 3])

In [64]:
# You can do these arithmetic operations on matrices of different sizes, 
# but only if one matrix has only one column or one row
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [70]:
# generate random array
rng = np.random.default_rng()
rng.random(3)
rng.random((3,2))
rng.integers(9,size = (2,4))

array([[5, 1, 3, 1],
       [0, 1, 0, 2]], dtype=int64)

In [72]:
# get unique items and count
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_value = np.unique(a)
unique_value

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
# get the index position of the items
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [75]:
# get the frequency of the values
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [76]:
# transpose the matrix
arr = np.arange(6).reshape((2, 3))
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [77]:
# the second method to transpose
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [78]:
# reserse the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [79]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [80]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [82]:
np.flip((arr_2d), axis = 1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [84]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [85]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [86]:
# reshape and flatten the multidimensional arrays
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
# save and load
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)

In [90]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
# import and export a csv
# the function also use with Pandas